# Usa a imagem oficial do Python
FROM python

# Define o diretório que vai ser usado
WORKDIR /app

# Copia o arquivo carguru.py para dentro do container
COPY carguru.py /app/carguru.py

# Executa os comandos dentro do container
CMD ["python", "carguru.py"]