# Usa a imagem oficial do Python
FROM python

# Define o diretório que vai ser usado
WORKDIR /sprint

# Copia o arquivo hash.py para dentro do container
COPY hash.py /sprint/hash.py

# Executa os comandos dentro do container
CMD ["python", "hash.py"]